version: "3.9"

volumes:
  data:

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn apps.main:app --host 0.0.0.0 --port 8005
    volumes:
      - .:/code/
    environment:
      - DATABASE_URL=postgres://root:admin@engagement_postgres:5436/engagement_database
      - SECRET_KEY=8c6bf0f1b38792f53b1eea89cdf30109a1eceba49d2f0258cd50d31ea4562da7
    ports:
      - 8005:8005
    
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: engagement_postgres
    image: postgres:alpine3.17
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "engagement_database"
      PGPORT: 5436
    ports:
      - "5436:5436"
    volumes:
      - data:/var/lib/postgresql/data
    restart: unless-stopped