version: "3.9"

volumes:
  data:

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn apps.main:app --host 0.0.0.0
    volumes:
      - .:/code/
    environment:
      - DATABASE_URL=postgres://root:admin@postgres:5432/database
      - SECRET_KEY=8c6bf0f1b38792f53b1eea89cdf30109a1eceba49d2f0258cd50d31ea4562da7
    ports:
      - 8000:8000
    
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres:alpine3.17
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "database"
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    restart: unless-stopped