from tortoise import BaseDBAsyncClient


async def upgrade(db: BaseDBAsyncClient) -> str:
    return """
        CREATE TABLE IF NOT EXISTS "notification" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "for_user_id" CHAR(36) NOT NULL,
    "type" VARCHAR(25) NOT NULL  /* POST_REACTION_RECEIVED: POST_REACTION_RECEIVED\nPOST_COMMENT_RECEIVED: POST_COMMENT_RECEIVED\nCONNECTION_RECOMMENDATION: CONNECTION_RECOMMENDATION\nPOST_RECOMMENDATION: POST_RECOMMENDATION\nSYSTEM_MESSAGE: SYSTEM_MESSAGE\nPROFILE_ACTIVITY: PROFILE_ACTIVITY\nUSER_CONNECTED: USER_CONNECTED */,
    "message" TEXT NOT NULL,
    "status" VARCHAR(9) NOT NULL  DEFAULT 'GENERATED' /* GENERATED: GENERATED\nSENDING: SENDING\nSENT: SENT\nVIEWED: VIEWED */,
    "created_at" TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP   DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "user_engagement" (
    "id" CHAR(36) NOT NULL  PRIMARY KEY,
    "created_at" TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    "created_by" CHAR(36),
    "updated_at" TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    "updated_by" CHAR(36),
    "user_id" CHAR(36) NOT NULL UNIQUE,
    "total_owned_posts" INT NOT NULL  DEFAULT 0,
    "total_post_views" INT NOT NULL  DEFAULT 0,
    "total_post_reactions" INT NOT NULL  DEFAULT 0,
    "total_post_comments" INT NOT NULL  DEFAULT 0,
    "engagement_score" REAL NOT NULL  DEFAULT 0,
    "status" VARCHAR(17) NOT NULL  DEFAULT 'ISOLATED' /* HIGHLY_ACTIVE: HIGHLY_ACTIVE\nMODERATELY_ACTIVE: MODERATELY_ACTIVE\nNORMALLY_ACTIVE: NORMALLY_ACTIVE\nLESS_ACTIVE: LESS_ACTIVE\nISOLATED: ISOLATED */,
    "summary" JSON NOT NULL
);
CREATE TABLE IF NOT EXISTS "aerich" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "version" VARCHAR(255) NOT NULL,
    "app" VARCHAR(100) NOT NULL,
    "content" JSON NOT NULL
);"""


async def downgrade(db: BaseDBAsyncClient) -> str:
    return """
        """
