from apps.core.enums import TextChoices, IntegerChoices


class StatusChoices(TextChoices):
    HIGHLY_ACTIVE = "HIGHLY_ACTIVE"
    MODERATELY_ACTIVE = "MODERATELY_ACTIVE"
    NORMALLY_ACTIVE = "NORMALLY_ACTIVE"
    LESS_ACTIVE = "LESS_ACTIVE"
    ISOLATED = "ISOLATED"


class InterestChoices(TextChoices):
    SPORTS = "SPORTS"
    NEWS = "NEWS"
    HEALTH = "HEALTH"
    POLITICS = "POLITICS"
    TRAVEL = "TRAVEL"
    FOOD = "FOOD"
    FICTION = "FICTION"
    TECHNOLOGY = "TECHNOLOGY"
    COMMUNICATION = "COMMUNICATION"
    INTERNATIONAL = "INTERNATIONAL"
    NATIONAL = "NATIONAL"
    CULTURAL = "CULTURAL"
    LIFE_STYLE = "LIFE_STYLE"
    FASHION = "FASHION"
    EDUCATIONAL = "EDUCATIONAL"
    PERSONAL_EVENT = "PERSONAL_EVENT"
    OTHER = "OTHER"
    MUSIC_AND_ART = "MUSIC_AND_ART"
    NOVEL_AND_POETRY = "NOVEL_AND_POETRY"
    BOOKS = "BOOKS"
    PROTEST = "PROTEST"
    SCIENTIFIC = "SCIENTIFIC"


# ranges of engagement levels
class EngagementLevels(IntegerChoices):
    HIGHLY_ACTIVE = 80
    MODERATELY_ACTIVE = 60
    NORMALLY_ACTIVE = 50
    LESS_ACTIVE = 20
    ISOLATED = 10


class NotificationStatusChoices(TextChoices):
    GENERATED = "GENERATED"
    SENDING = "SENDING"
    SENT = "SENT"
    VIEWED = "VIEWED"


class NotificationTypes(TextChoices):
    POST_REACTION_RECEIVED = "POST_REACTION_RECEIVED"
    POST_COMMENT_RECEIVED = "POST_COMMENT_RECEIVED"
    CONNECTION_RECOMMENDATION = "CONNECTION_RECOMMENDATION"
    POST_RECOMMENDATION = "POST_RECOMMENDATION"
    SYSTEM_MESSAGE = "SYSTEM_MESSAGE"
    PROFILE_ACTIVITY = "PROFILE_ACTIVITY"
    USER_CONNECTED = "USER_CONNECTED"
